Repository projectceladon/external-mesa, pull requests merged in 2024-07, with the labels that each got.

#106 iris/anv: Disable HW emulation for ASTC when running CTS on MTL platform
  src/gallium/auxiliary/util/u_screen.c
  src/gallium/drivers/iris/iris_screen.c
  src/gallium/include/pipe/p_defines.h
  src/intel/vulkan/anv_device.c
  src/mesa/state_tracker/st_context.c
  src/util/00-mesa-defaults.conf
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#108 egl/android: Fix unsupported egl config r10g10b10a2, recordable_android=0 for media cts
  src/egl/drivers/dri2/platform_android.c
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#109 Fix cts DecodeGlAccuracyTest fail
  src/util/u_gralloc/u_gralloc_imapper4_api.cpp
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#112 Added workflows
  .github/workflows/run_ci_checks.yaml
Labels: Invalid commit message

#113 Revert "egl/android: Fix unsupported egl config r10g10b10a2, recordab…
  src/egl/drivers/dri2/platform_android.c
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#110 [Android 12] Implement VK_EXT_device_memory_report
  src/intel/vulkan/anv_device.c
  src/intel/vulkan/anv_private.h
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#111 [Android 12] Revert "INTERNAL: Revert 530ae32c:iris:Fix to release BO immediately …
  src/gallium/drivers/iris/iris_bufmgr.c
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#115 Revert "egl/android: Fix unsupported egl config r10g10b10a2, recordab…
  src/egl/drivers/dri2/platform_android.c
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#116 [Android14] Implement VK_EXT_device_memory_report
  src/intel/vulkan/anv_device.c
  src/intel/vulkan/anv_private.h
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#117 [Android14] Revert "INTERNAL: Revert 530ae32c:iris:Fix to release BO immediately …
  src/gallium/drivers/iris/iris_bufmgr.c
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#124 anv: Add idep_genxml to dependencies of grl_genX_libs
  src/intel/vulkan/grl/meson.build
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#123 Add legacy dataspace value supporting
  src/util/u_gralloc/u_gralloc_imapper4_api.cpp
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful
